version: '3.4'

services:
#  fin-control-be:
#    build:
#      context: .
#      dockerfile: Dockerfile
#      target: development
#    env_file:
#      - local-docker.env
#    volumes:
#      - .:/usr/src/app
#      - /usr/src/app/node_modules
#      - /usr/src/app/prisma/client
#    ports:
#      - '3001:3000'
#      - '9229:9229'
#    command: npm run start:dev
#    depends_on:
#      - redis
#      - cockroachdb

  redis:
    image: redis:latest
    ports:
      - '6379:6379'

  cockroachdb:
    image: cockroachdb/cockroach:latest
    ports:
      - '26257:26257'
      - '8081:8080'
    volumes:
      - "./cockroach-data/crdb:/cockroach/cockroach-data"
    command: start-single-node --insecure