version: '3.8'

networks:
  monitoring:
    driver: bridge
services:
  #  fin-control-be:
  #    build:
  #      context: .
  #      dockerfile: Dockerfile
  #    env_file:
  #      - local-docker.env
  #    volumes:
  #      - .:/usr/src/app
  #      - /usr/src/app/node_modules
  #      - /usr/src/app/prisma/client
  #    ports:
  #      - '3001:3000'
  #      - '9229:9229'
  #    depends_on:
  #      - valkey
  #      - postgres

  valkey:
    image: bitnami/valkey:8.1.2
    restart: unless-stopped
    ports:
      - '6379:6379'
#    network_mode: host  # Required for clustering, optional otherwise
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - VALKEY_IO_THREADS_DO_READS=yes
      - VALKEY_IO_THREADS=4

  postgres:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_DB: fin_control
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./local-infrastructure/data/postgres-data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus:v2.50.0
    container_name: prometheus
    restart: unless-stopped
    ports:
      - '9090:9090'
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    volumes:
      - ./local-infrastructure/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - ./local-infrastructure/data/prometheus-data:/prometheus

  grafana:
    image: grafana/grafana-oss:10.3.3
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3001:3000'
    volumes:
      - ./local-infrastructure/data/grafana-data:/var/lib/grafana

  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.5.0
    container_name: node_exporter
    restart: unless-stopped
    command: '--path.rootfs=/host'
    pid: host
    volumes:
      - /:/host:ro,rslave

  sonarqube:
    image: sonarqube
    restart: unless-stopped
    ports:
      - '9000:9000'
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    volumes:
      - ./local-infrastructure/data/sonarqube-data:/opt/sonarqube/data
      - ./local-infrastructure/data/sonarqube-extensions:/opt/sonarqube/extensions
