version: '3.8'

networks:
  monitoring:
    driver: bridge
services:
  #  fin-control-be:
  #    build:
  #      context: .
  #      dockerfile: Dockerfile
  #    env_file:
  #      - local-docker.env
  #    volumes:
  #      - .:/usr/src/app
  #      - /usr/src/app/node_modules
  #      - /usr/src/app/prisma/client
  #    ports:
  #      - '3001:3000'
  #      - '9229:9229'
  #    depends_on:
  #      - redis
  #      - cockroachdb

  redis:
    image: redis:7.0.11
    restart: unless-stopped
    ports:
      - '6379:6379'


  cockroachdb:
    image: cockroachdb/cockroach:v22.2.8
    ports:
      - '26257:26257'
      - '8081:8080'
    volumes:
      - ./local-infrastructure/data/cockroach-data/crdb:/cockroach/cockroach-data
    restart: unless-stopped
    command: start-single-node --insecure

  prometheus:
    image: prom/prometheus:v2.50.0
    container_name: prometheus
    ports:
      - '9090:9090'
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    volumes:
      - ./local-infrastructure/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - ./local-infrastructure/data/prometheus-data:/prometheus
    restart: unless-stopped

  grafana:
    image: grafana/grafana-oss:10.3.3
    container_name: grafana
    ports:
      - '3001:3000'
    volumes:
      - ./local-infrastructure/data/grafana-data:/var/lib/grafana
    restart: unless-stopped

  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.5.0
    container_name: node_exporter
    command: '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - /:/host:ro,rslave