scrape_configs:
  - job_name: 'fin-control-be'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:3000']
    metrics_path: '/metrics'
  - job_name: 'node-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['node_exporter:9100']